# Generated by Django 2.2.16 on 2022-04-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220427_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_rights',
            new_name='role',
        ),
    ]
